# Based on the current cross-platform JVM mod template.
modName = aurora-ai-companion
modFetch = aurora.fetched
modGenSrc = aurora.entities.comp
modGen = aurora.gen
modArtifact = AuroraAICompanion
entVersion = v159.7.6
mindustryVersion = v159.7
androidSdkVersion = 37.0
androidBuildVersion = 37.0.0
androidMinVersion = 21
org.gradle.parallel = true
org.gradle.jvmargs = -Dfile.encoding=UTF-8
org.gradle.configuration-cache = true
projectVersion = 2.0.4.6
